version: '3'
services:
  client:
    container_name: client
    restart: always
    build: ./client
    ports:
      - "80:3000"
    networks:
      - backend
  server:
    container_name: server
    restart: always
    build: ./server
    ports:
      - "8080:8080"
      - "8081:8081"
    volumes:
      - /app/node_modules
    depends_on:
      - mongo
    networks:
      - backend
    networks:
      backend:
        aliases:
          - server
  mongo:
    build: ./db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=dine
      - MONGO_INITDB_ROOT_PASSWORD=out
      - MONGO_INITDB_DATABASE=dine
    ports:
      - 27017:27017
    networks:
      - backend
    networks:
      backend:
        aliases:
          - mongo

networks:
  backend: